/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmView;

import bmController.Controller;
import bmModel.ClienteData;
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.lang.reflect.Method;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javafx.scene.control.Control;
import javax.swing.JComboBox;


/**
 *
 * @author az
 */
public class Menu extends javax.swing.JFrame {

    public int i;

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setAlwaysOnTop(true);
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
        i = 0;
        
        //Toolkit tk = Toolkit.getDefaultToolkit();
        //int xsize = (int) tk.getScreenSize().getWidth();
        //int ysize = (int) tk.getScreenSize().getWidth();
        
        this.setSize(1160, 800);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        LabelEmpresa = new javax.swing.JLabel();
        jBClientes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBMenu = new javax.swing.JButton();
        jBFunc = new javax.swing.JButton();
        jBEstoque = new javax.swing.JButton();
        jbTrans = new javax.swing.JButton();
        jPanelSelec = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        LoginPanelBack1 = new javax.swing.JPanel();
        LoginPanelBack2 = new javax.swing.JPanel();
        jBEntrar = new javax.swing.JButton();
        InfoSenha = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        PasswordIcon = new javax.swing.JLabel();
        UserIcon = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        InfoUser = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        Clientes = new javax.swing.JPanel();
        jBNovoCliente = new javax.swing.JButton();
        jTPesquisar = new javax.swing.JTextField();
        jCBOrdenar = new javax.swing.JComboBox<>();
        jCBAcao = new javax.swing.JComboBox<>();
        jP1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jTNome1 = new javax.swing.JTextField();
        jTNome2 = new javax.swing.JTextField();
        jTNome3 = new javax.swing.JTextField();
        jTNome4 = new javax.swing.JTextField();
        jTNome5 = new javax.swing.JTextField();
        jTNome6 = new javax.swing.JTextField();
        jTNome7 = new javax.swing.JTextField();
        jTNome8 = new javax.swing.JTextField();
        jTNome9 = new javax.swing.JTextField();
        jTNome10 = new javax.swing.JTextField();
        jTEmpresa1 = new javax.swing.JTextField();
        jTEmpresa2 = new javax.swing.JTextField();
        jTEmpresa3 = new javax.swing.JTextField();
        jTEmpresa4 = new javax.swing.JTextField();
        jTEmpresa5 = new javax.swing.JTextField();
        jTEmpresa6 = new javax.swing.JTextField();
        jTEmpresa7 = new javax.swing.JTextField();
        jTEmpresa8 = new javax.swing.JTextField();
        jTEmpresa9 = new javax.swing.JTextField();
        jTEmpresa10 = new javax.swing.JTextField();
        jTCel1 = new javax.swing.JTextField();
        jTCel2 = new javax.swing.JTextField();
        jTCel3 = new javax.swing.JTextField();
        jTCel4 = new javax.swing.JTextField();
        jTCel5 = new javax.swing.JTextField();
        jTCel6 = new javax.swing.JTextField();
        jTCel7 = new javax.swing.JTextField();
        jTCel8 = new javax.swing.JTextField();
        jTCel9 = new javax.swing.JTextField();
        jTCel10 = new javax.swing.JTextField();
        jTTel1 = new javax.swing.JTextField();
        jTTel2 = new javax.swing.JTextField();
        jTTel3 = new javax.swing.JTextField();
        jTTel4 = new javax.swing.JTextField();
        jTTel5 = new javax.swing.JTextField();
        jTTel6 = new javax.swing.JTextField();
        jTTel7 = new javax.swing.JTextField();
        jTTel8 = new javax.swing.JTextField();
        jTTel9 = new javax.swing.JTextField();
        jTTel10 = new javax.swing.JTextField();
        jBAvancar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLPag = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NovoCliente = new javax.swing.JPanel();
        Cliente = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jTTelefone = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTEmpresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTCelular = new javax.swing.JTextField();
        jTEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTComplemento = new javax.swing.JTextField();
        jTRua = new javax.swing.JTextField();
        jTCidade = new javax.swing.JTextField();
        jTCEP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTEstado = new javax.swing.JTextField();
        Funcionários = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Estoque = new javax.swing.JPanel();
        Transações = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMenu.setBackground(new java.awt.Color(109, 183, 112));
        jPanelMenu.setForeground(new java.awt.Color(254, 254, 254));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmView/Logo2.png"))); // NOI18N

        LabelEmpresa.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        LabelEmpresa.setForeground(new java.awt.Color(254, 254, 254));
        LabelEmpresa.setText("Brasil Mudas");

        jBClientes.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jBClientes.setText("Clientes");
        jBClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClientesActionPerformed(evt);
            }
        });

        jBMenu.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jBMenu.setText("Menu");
        jBMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuActionPerformed(evt);
            }
        });

        jBFunc.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jBFunc.setText("Funcionários");

        jBEstoque.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jBEstoque.setText("Estoque");

        jbTrans.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jbTrans.setText("Transações");

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logo)
                            .addComponent(jLabel3)))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(LabelEmpresa)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jBFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelEmpresa)
                .addGap(23, 23, 23)
                .addComponent(jBMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSelec.setLayout(new java.awt.CardLayout());

        LoginPanelBack1.setBackground(new java.awt.Color(72, 151, 69));

        LoginPanelBack2.setBackground(new java.awt.Color(48, 121, 39));

        jBEntrar.setText("Entrar");
        jBEntrar.setActionCommand("FazerLogin");
        jBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrarActionPerformed(evt);
            }
        });

        InfoSenha.setForeground(new java.awt.Color(254, 254, 254));
        InfoSenha.setText("Professor, digite aqui sua senha do mysql.");

        PasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmView/Password.png"))); // NOI18N

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmView/Login.png"))); // NOI18N

        user.setText("root");

        InfoUser.setForeground(new java.awt.Color(254, 254, 254));
        InfoUser.setText("Trocar se seu usuário no mysql for diferente de root.");

        javax.swing.GroupLayout LoginPanelBack2Layout = new javax.swing.GroupLayout(LoginPanelBack2);
        LoginPanelBack2.setLayout(LoginPanelBack2Layout);
        LoginPanelBack2Layout.setHorizontalGroup(
            LoginPanelBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelBack2Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addGroup(LoginPanelBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelBack2Layout.createSequentialGroup()
                        .addGroup(LoginPanelBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordIcon)
                            .addComponent(UserIcon))
                        .addGap(28, 28, 28)
                        .addGroup(LoginPanelBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(user, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(InfoSenha)
                            .addComponent(InfoUser))
                        .addGap(40, 40, 40))
                    .addComponent(jBEntrar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(232, 232, 232))
        );
        LoginPanelBack2Layout.setVerticalGroup(
            LoginPanelBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelBack2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(LoginPanelBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelBack2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InfoUser)
                        .addGap(39, 39, 39)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InfoSenha))
                    .addGroup(LoginPanelBack2Layout.createSequentialGroup()
                        .addComponent(UserIcon)
                        .addGap(36, 36, 36)
                        .addComponent(PasswordIcon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jBEntrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout LoginPanelBack1Layout = new javax.swing.GroupLayout(LoginPanelBack1);
        LoginPanelBack1.setLayout(LoginPanelBack1Layout);
        LoginPanelBack1Layout.setHorizontalGroup(
            LoginPanelBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanelBack2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LoginPanelBack1Layout.setVerticalGroup(
            LoginPanelBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelBack1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(LoginPanelBack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addComponent(LoginPanelBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanelBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelSelec.add(Login, "card8");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanelSelec.add(Menu, "Menu");

        Clientes.setBackground(new java.awt.Color(250, 255, 250));

        jBNovoCliente.setText("Novo Cliente");
        jBNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoClienteActionPerformed(evt);
            }
        });

        jCBOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenar por Nome" }));

        jCBAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Deletar" }));
        jCBAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAcaoActionPerformed(evt);
            }
        });

        jP1.setBackground(new java.awt.Color(230, 230, 230));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox1.setActionCommand("ComboBox1");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox2.setActionCommand("ComboBox2");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox3.setActionCommand("ComboBox3");
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox4.setActionCommand("ComboBox4");
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox5.setActionCommand("ComboBox5");
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox6.setActionCommand("ComboBox6");
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox7.setActionCommand("ComboBox7");
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox8.setActionCommand("ComboBox8");
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox9.setActionCommand("ComboBox9");
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ações", "Fazer pedido", "Receber pagamento", "Editar Contato", "Deletar Contato" }));
        jComboBox10.setActionCommand("ComboBox10");
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });

        jTNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNome1ActionPerformed(evt);
            }
        });

        jTCel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCel1ActionPerformed(evt);
            }
        });

        jTCel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCel6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP1Layout = new javax.swing.GroupLayout(jP1);
        jP1.setLayout(jP1Layout);
        jP1Layout.setHorizontalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jTNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jP1Layout.createSequentialGroup()
                            .addComponent(jCheckBox3)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP1Layout.createSequentialGroup()
                            .addComponent(jCheckBox5)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP1Layout.createSequentialGroup()
                            .addComponent(jCheckBox4)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP1Layout.createSequentialGroup()
                            .addComponent(jCheckBox10)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP1Layout.createSequentialGroup()
                            .addComponent(jCheckBox9)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP1Layout.createSequentialGroup()
                            .addComponent(jCheckBox8)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP1Layout.createSequentialGroup()
                            .addComponent(jCheckBox7)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP1Layout.createSequentialGroup()
                            .addComponent(jCheckBox6)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jTNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTCel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTEmpresa1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTEmpresa4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTEmpresa3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTEmpresa5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTEmpresa6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTEmpresa7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTEmpresa8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTEmpresa9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTEmpresa10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jP1Layout.setVerticalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addComponent(jTTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTTel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jTTel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTTel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTTel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTTel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTTel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTTel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTTel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addComponent(jTEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTEmpresa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jTEmpresa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTEmpresa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTEmpresa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTEmpresa7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTEmpresa8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTEmpresa9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTEmpresa10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jTCel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTCel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jTCel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTCel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTCel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTCel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTCel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTCel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTCel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTCel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTNome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNome2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNome3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNome4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox5))
                        .addGap(18, 18, 18)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCheckBox6)
                                .addComponent(jTNome6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTNome7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTNome8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox8, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTNome9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox9, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNome10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox10))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jBAvancar.setText("Avançar");
        jBAvancar.setActionCommand("Avancar");
        jBAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAvancarActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel2.setText("Telefone");

        jLPag.setText("Página");

        jLabel15.setText("Celular");

        jLabel16.setText("Empresa");

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientesLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel2)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel15)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel16))
                    .addGroup(ClientesLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jCBAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jCBOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesLayout.createSequentialGroup()
                        .addComponent(jBNovoCliente)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesLayout.createSequentialGroup()
                        .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesLayout.createSequentialGroup()
                                .addComponent(jBVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAvancar)
                                .addGap(14, 14, 14))
                            .addGroup(ClientesLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLPag)))
                        .addContainerGap())))
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBNovoCliente)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientesLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)))
                    .addGroup(ClientesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLPag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAvancar)
                    .addComponent(jBVoltar))
                .addContainerGap())
        );

        jPanelSelec.add(Clientes, "Clientes");

        Cliente.setText("Nome");

        Telefone.setText("Telefone");

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Novo Cliente");

        jLabel5.setText("Empresa");

        jLabel7.setText("Celular");

        jLabel8.setText("Email");

        jLabel9.setText("Endereço");

        jLabel10.setText("Rua");

        jLabel11.setText("Complemento");

        jLabel12.setText("Cidade");

        jLabel13.setText("Estado");

        jLabel14.setText("CEP");

        javax.swing.GroupLayout NovoClienteLayout = new javax.swing.GroupLayout(NovoCliente);
        NovoCliente.setLayout(NovoClienteLayout);
        NovoClienteLayout.setHorizontalGroup(
            NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NovoClienteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelar)
                .addGap(18, 18, 18)
                .addComponent(jBSalvar)
                .addGap(29, 29, 29))
            .addGroup(NovoClienteLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addGroup(NovoClienteLayout.createSequentialGroup()
                        .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NovoClienteLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(Cliente))
                            .addComponent(Telefone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTNome)
                                .addComponent(jTEmpresa)
                                .addComponent(jTTelefone)
                                .addComponent(jTEmail)
                                .addComponent(jTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(603, Short.MAX_VALUE))
        );
        NovoClienteLayout.setVerticalGroup(
            NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NovoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cliente))
                .addGap(30, 30, 30)
                .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefone))
                .addGap(30, 30, 30)
                .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NovoClienteLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NovoClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(30, 30, 30)
                        .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(30, 30, 30)))
                .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(8, 8, 8)
                .addGroup(NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalvar)
                    .addComponent(jBCancelar))
                .addGap(33, 33, 33))
        );

        jPanelSelec.add(NovoCliente, "NovoCliente");

        jLabel17.setText("Nome");

        jLabel18.setText("Inicio de Contrato");

        jLabel19.setText("C.P.F");

        jLabel20.setText("Telefone");

        jLabel21.setText("Celular");

        javax.swing.GroupLayout FuncionáriosLayout = new javax.swing.GroupLayout(Funcionários);
        Funcionários.setLayout(FuncionáriosLayout);
        FuncionáriosLayout.setHorizontalGroup(
            FuncionáriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncionáriosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(FuncionáriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addContainerGap(872, Short.MAX_VALUE))
        );
        FuncionáriosLayout.setVerticalGroup(
            FuncionáriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncionáriosLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        jPanelSelec.add(Funcionários, "Funcionários");

        javax.swing.GroupLayout EstoqueLayout = new javax.swing.GroupLayout(Estoque);
        Estoque.setLayout(EstoqueLayout);
        EstoqueLayout.setHorizontalGroup(
            EstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
        );
        EstoqueLayout.setVerticalGroup(
            EstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanelSelec.add(Estoque, "Estoque");

        javax.swing.GroupLayout TransaçõesLayout = new javax.swing.GroupLayout(Transações);
        Transações.setLayout(TransaçõesLayout);
        TransaçõesLayout.setHorizontalGroup(
            TransaçõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
        );
        TransaçõesLayout.setVerticalGroup(
            TransaçõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanelSelec.add(Transações, "Transações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jBClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClientesActionPerformed
        
    }//GEN-LAST:event_jBClientesActionPerformed

    private void jCBAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBAcaoActionPerformed

    private void jBNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoClienteActionPerformed
    
    }//GEN-LAST:event_jBNovoClienteActionPerformed

    private void jBMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuActionPerformed

    }//GEN-LAST:event_jBMenuActionPerformed

    private void jBAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAvancarActionPerformed
        
    }//GEN-LAST:event_jBAvancarActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed

    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed

    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTCel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCel6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCel6ActionPerformed

    private void jTCel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCel1ActionPerformed

    private void jTNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNome1ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed

    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed

    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed

    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed

    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed

    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed

    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed

    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed

    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrarActionPerformed

    }//GEN-LAST:event_jBEntrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cliente;
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Estoque;
    private javax.swing.JPanel Funcionários;
    private javax.swing.JLabel InfoSenha;
    private javax.swing.JLabel InfoUser;
    private javax.swing.JLabel LabelEmpresa;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel LoginPanelBack1;
    private javax.swing.JPanel LoginPanelBack2;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel NovoCliente;
    private javax.swing.JLabel PasswordIcon;
    private javax.swing.JLabel Telefone;
    private javax.swing.JPanel Transações;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JButton jBAvancar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBClientes;
    private javax.swing.JButton jBEntrar;
    private javax.swing.JButton jBEstoque;
    private javax.swing.JButton jBFunc;
    private javax.swing.JButton jBMenu;
    private javax.swing.JButton jBNovoCliente;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox<String> jCBAcao;
    private javax.swing.JComboBox<String> jCBOrdenar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLPag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP1;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelSelec;
    private javax.swing.JTextField jTCEP;
    private javax.swing.JTextField jTCel1;
    private javax.swing.JTextField jTCel10;
    private javax.swing.JTextField jTCel2;
    private javax.swing.JTextField jTCel3;
    private javax.swing.JTextField jTCel4;
    private javax.swing.JTextField jTCel5;
    private javax.swing.JTextField jTCel6;
    private javax.swing.JTextField jTCel7;
    private javax.swing.JTextField jTCel8;
    private javax.swing.JTextField jTCel9;
    private javax.swing.JTextField jTCelular;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextField jTComplemento;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTEmpresa;
    private javax.swing.JTextField jTEmpresa1;
    private javax.swing.JTextField jTEmpresa10;
    private javax.swing.JTextField jTEmpresa2;
    private javax.swing.JTextField jTEmpresa3;
    private javax.swing.JTextField jTEmpresa4;
    private javax.swing.JTextField jTEmpresa5;
    private javax.swing.JTextField jTEmpresa6;
    private javax.swing.JTextField jTEmpresa7;
    private javax.swing.JTextField jTEmpresa8;
    private javax.swing.JTextField jTEmpresa9;
    private javax.swing.JTextField jTEstado;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNome1;
    private javax.swing.JTextField jTNome10;
    private javax.swing.JTextField jTNome2;
    private javax.swing.JTextField jTNome3;
    private javax.swing.JTextField jTNome4;
    private javax.swing.JTextField jTNome5;
    private javax.swing.JTextField jTNome6;
    private javax.swing.JTextField jTNome7;
    private javax.swing.JTextField jTNome8;
    private javax.swing.JTextField jTNome9;
    private javax.swing.JTextField jTPesquisar;
    private javax.swing.JTextField jTRua;
    private javax.swing.JTextField jTTel1;
    private javax.swing.JTextField jTTel10;
    private javax.swing.JTextField jTTel2;
    private javax.swing.JTextField jTTel3;
    private javax.swing.JTextField jTTel4;
    private javax.swing.JTextField jTTel5;
    private javax.swing.JTextField jTTel6;
    private javax.swing.JTextField jTTel7;
    private javax.swing.JTextField jTTel8;
    private javax.swing.JTextField jTTel9;
    private javax.swing.JTextField jTTelefone;
    private javax.swing.JButton jbTrans;
    private javax.swing.JTextField password;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    public void PreencherCamposMenuClientes(ClienteData ClienteData) {
        LimparCamposMenuClientes();
        int NumContatos = ClienteData.getNum();
        if (i < NumContatos) {
            jTNome1.setText(ClienteData.getNome().get(i));
            
            if(ClienteData.getTelefone().get(i) == 0)
                jTTel1.setText("");
            else    
                jTTel1.setText(ClienteData.getTelefone().get(i).toString());
            
            if(ClienteData.getCelular().get(i) == 0)
                jTCel1.setText("");
            else   
                jTCel1.setText(ClienteData.getCelular().get(i).toString());
            
            jTEmpresa1.setText(ClienteData.getEmpresa().get(i));
            if (i + 1 < NumContatos) {
                jTNome2.setText(ClienteData.getNome().get(i + 1));
                
                if (ClienteData.getTelefone().get(i+1) == 0)
                    jTTel2.setText("");
                else 
                    jTTel2.setText(ClienteData.getTelefone().get(i+1).toString());
                
                if (ClienteData.getCelular().get(i) == 0)
                    jTCel2.setText("");
                else 
                    jTCel2.setText(ClienteData.getCelular().get(i).toString());
                
                jTEmpresa2.setText(ClienteData.getEmpresa().get(i + 1));
                if (i + 2 < NumContatos) {
                    jTNome3.setText(ClienteData.getNome().get(i + 2));
                    
                    if (ClienteData.getTelefone().get(i+2) == 0)
                        jTTel3.setText("");
                    else
                        jTTel3.setText(ClienteData.getTelefone().get(i+2).toString());
                    
                    if (ClienteData.getCelular().get(i+2) == 0)
                        jTCel3.setText("");
                    else 
                        jTCel3.setText(ClienteData.getCelular().get(i+2).toString());
                    
                    jTEmpresa3.setText(ClienteData.getEmpresa().get(i + 2));
                    if (i + 3 < NumContatos) {
                        jTNome4.setText(ClienteData.getNome().get(i + 3));
                        
                        if(ClienteData.getTelefone().get(i+3) == 0)
                            jTTel4.setText("");
                        else    
                            jTTel4.setText(ClienteData.getTelefone().get(i+3).toString());

                        if(ClienteData.getCelular().get(i+3) == 0)
                            jTCel4.setText("");
                        else   
                            jTCel4.setText(ClienteData.getCelular().get(i+3).toString());
                            
                        jTEmpresa4.setText(ClienteData.getEmpresa().get(i + 3));
                        if (i + 4 < NumContatos) {
                            jTNome5.setText(ClienteData.getNome().get(i + 4));
                            
                            if(ClienteData.getTelefone().get(i+4) == 0)
                                jTTel5.setText("");
                            else    
                                jTTel5.setText(ClienteData.getTelefone().get(i+4).toString());

                            if(ClienteData.getCelular().get(i+4) == 0)
                                jTCel5.setText("");
                            else   
                                jTCel5.setText(ClienteData.getCelular().get(i+4).toString());
                            
                            jTEmpresa5.setText(ClienteData.getEmpresa().get(i+4));
                            if (i + 5< NumContatos) {
                                jTNome6.setText(ClienteData.getNome().get(i+5));
                                if(ClienteData.getTelefone().get(i+5) == 0)
                                    jTTel6.setText("");
                                else    
                                    jTTel6.setText(ClienteData.getTelefone().get(i+5).toString());

                                if(ClienteData.getCelular().get(i+5) == 0)
                                    jTCel6.setText("");
                                else   
                                    jTCel6.setText(ClienteData.getCelular().get(i+5).toString());
                                
                                jTEmpresa6.setText(ClienteData.getEmpresa().get(i+ 5));
                                if (i + 6 < NumContatos) {
                                    jTNome7.setText(ClienteData.getNome().get(i + 6));
                                    
                                    if(ClienteData.getTelefone().get(i+6) == 0)
                                        jTTel7.setText("");
                                    else    
                                        jTTel7.setText(ClienteData.getTelefone().get(i+6).toString());

                                    if(ClienteData.getCelular().get(i+6) == 0)
                                        jTCel7.setText("");
                                    else   
                                        jTCel7.setText(ClienteData.getCelular().get(i+6).toString());
                                    
                                    jTEmpresa7.setText(ClienteData.getEmpresa().get(i+6));
                                    if (i + 7 < NumContatos) {
                                        jTNome8.setText(ClienteData.getNome().get(i + 7));
                                        
                                        if(ClienteData.getTelefone().get(i+7) == 0)
                                            jTTel8.setText("");
                                        else    
                                            jTTel8.setText(ClienteData.getTelefone().get(i+7).toString());

                                        if(ClienteData.getCelular().get(i+7) == 0)
                                            jTCel8.setText("");
                                        else   
                                            jTCel8.setText(ClienteData.getCelular().get(i+7).toString());
                                        
                                        jTEmpresa8.setText(ClienteData.getEmpresa().get(i+7));
                                        if (i + 8 < NumContatos) {
                                            jTNome9.setText(ClienteData.getNome().get(i + 8));
                                            
                                            if(ClienteData.getTelefone().get(i+8) == 0)
                                                jTTel9.setText("");
                                            else    
                                                jTTel9.setText(ClienteData.getTelefone().get(i+8).toString());

                                            if(ClienteData.getCelular().get(i+8) == 0)
                                                jTCel9.setText("");
                                            else   
                                                jTCel9.setText(ClienteData.getCelular().get(i+8).toString());
                                            
                                            jTEmpresa9.setText(ClienteData.getEmpresa().get(i+8));
                                            if (i + 9 < NumContatos) {
                                                jTNome10.setText(ClienteData.getNome().get(i + 9));
                                                if(ClienteData.getTelefone().get(i+9) == 0)
                                                    jTTel10.setText("");
                                                else    
                                                    jTTel10.setText(ClienteData.getTelefone().get(i+9).toString());

                                                if(ClienteData.getCelular().get(i+9) == 0)
                                                    jTCel10.setText("");
                                                else   
                                                    jTCel10.setText(ClienteData.getCelular().get(i+9).toString());
                                                jTEmpresa10.setText(ClienteData.getEmpresa().get(i + 9));
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    public void LimparCamposMenuClientes() {
        jTNome1.setText("");jTNome2.setText("");jTNome3.setText("");jTNome4.setText("");jTNome5.setText("");
        jTNome6.setText("");jTNome7.setText("");jTNome8.setText("");jTNome9.setText("");jTNome10.setText("");
        
        jTTel1.setText("");jTTel2.setText("");jTTel3.setText("");jTTel4.setText("");jTTel5.setText("");
        jTTel6.setText("");jTTel7.setText("");jTTel8.setText("");jTTel9.setText("");jTTel10.setText("");
                
        jTCel1.setText("");jTCel2.setText("");jTCel3.setText("");jTCel4.setText("");jTCel5.setText("");
        jTCel6.setText("");jTCel7.setText("");jTCel8.setText("");jTCel9.setText("");jTCel10.setText("");
                
        jTEmpresa1.setText("");jTEmpresa2.setText("");jTEmpresa3.setText("");jTEmpresa4.setText("");jTEmpresa5.setText("");
        jTEmpresa6.setText("");jTEmpresa7.setText("");jTEmpresa8.setText("");jTEmpresa9.setText("");jTEmpresa10.setText("");

    }

    public void DisplayJPanelClientes() {
        CardLayout Card = (CardLayout) jPanelSelec.getLayout();
        Card.show(jPanelSelec, "Clientes");
        
        jLPag.setText("Página:"+(i/10+1)+"");
        
    }
    
    public void addController(Controller Control) {
        
        //Botões do Login
        jBEntrar.addActionListener(Control);
        
        //Botões do Menu
        jBMenu.addActionListener(Control);
        jBClientes.addActionListener(Control);
        
        //Botões Menu Cliente.
        jBAvancar.addActionListener(Control);
        jBVoltar.addActionListener(Control);
        jBNovoCliente.addActionListener(Control);
        jComboBox1.addActionListener(Control);
        jComboBox2.addActionListener(Control);
        jComboBox3.addActionListener(Control);
        jComboBox4.addActionListener(Control);
        jComboBox5.addActionListener(Control);
        jComboBox6.addActionListener(Control);
        jComboBox7.addActionListener(Control);
        jComboBox8.addActionListener(Control);
        jComboBox9.addActionListener(Control);
        jComboBox10.addActionListener(Control);
        
        //Botões Salvar Cliente   
        jBSalvar.addActionListener(Control);
        jBCancelar.addActionListener(Control);
        

    }

    public void ViewMenu() {
        jBVoltar.setEnabled(false);
        DisplayJPanelClientes();
    }

    public boolean SClientes(ArrayList<String> A){
        if(jTNome.getText().equals("")){
            Mensagens("Erro, Preencha o campo Nome.");
            return false;
        }
        else    
            A.add(jTNome.getText());

        if (!jTTelefone.getText().equals("")) {
            A.add(jTTelefone.getText());
        } else {
            A.add("DEFAULT");
        }
        if (!jTCelular.getText().equals("")) {
            A.add(jTCelular.getText());
        } else {
            A.add("DEFAULT");
        }
        
        A.add(jTEmpresa.getText());
   
        
        A.add(jTCidade.getText());

        
        A.add(jTEstado.getText());
   
        if (!jTCEP.getText().equals("")) {
            A.add(jTCEP.getText());
        } else {
            A.add("DEFAULT");
        }

        A.add(jTRua.getText());
   

        A.add(jTComplemento.getText());


        A.add(jTEmail.getText());


        jTNome.setText("");
        jTTelefone.setText("");
        jTCelular.setText("");
        jTEmpresa.setText("");
        jTCidade.setText("");
        jTCEP.setText("");
        jTEstado.setText("");
        jTRua.setText("");
        jTComplemento.setText("");
        jTEmail.setText("");
        
        return true;
    }
    public void DisplayJPanelNovoCliente(){
        CardLayout Card = (CardLayout) jPanelSelec.getLayout();
        Card.show(jPanelSelec, "NovoCliente");
    }
    
    public void Mensagens(String Mensagem) {
        JOptionPane.showMessageDialog(this, Mensagem);
    }
    
    
    public int getSelectedIndex(int CB){
        int Index;
        if (CB==1){
            Index = jComboBox1.getSelectedIndex();
            jComboBox1.setSelectedIndex(0);
            jComboBox1.hidePopup();
            return Index;
        }
        else if (CB==2){
            Index = jComboBox2.getSelectedIndex();
            jComboBox2.setSelectedIndex(0);
            jComboBox2.hidePopup();
            return Index;
        }
        else if (CB==3){
            Index = jComboBox3.getSelectedIndex();
            jComboBox3.setSelectedIndex(0);
            jComboBox3.hidePopup();
            return Index;
        }
        else if (CB==4){
            Index = jComboBox4.getSelectedIndex();
            jComboBox4.setSelectedIndex(0);
            jComboBox4.hidePopup();
            return Index;
        }
        else if (CB==5){
            Index = jComboBox5.getSelectedIndex();
            jComboBox5.setSelectedIndex(0);
            jComboBox5.hidePopup();
            return Index;
        }
        else if (CB==6){
            Index = jComboBox6.getSelectedIndex();
            jComboBox6.setSelectedIndex(0);
            jComboBox6.hidePopup();
            return Index;
        }
        else if (CB==7){
            Index = jComboBox7.getSelectedIndex();
            jComboBox7.setSelectedIndex(0);
            jComboBox7.hidePopup();
            return Index;
        }
        else if (CB==8){
            Index = jComboBox8.getSelectedIndex();
            jComboBox8.setSelectedIndex(0);
            jComboBox8.hidePopup();
            return Index;
        }
        else if (CB==9){
            Index = jComboBox9.getSelectedIndex();
            jComboBox9.setSelectedIndex(0);
            jComboBox9.hidePopup();
            return Index;
        }
        else if (CB==10){
            Index = jComboBox10.getSelectedIndex();
            jComboBox10.setSelectedIndex(0);
            jComboBox10.hidePopup();
            return Index;
        }

        else 
            return -1;
    }
    public void Avancar(){
        jBVoltar.setEnabled(true);
        i += 10;
        jLPag.setText("Página:"+(i/10+1)+"");
        
    }
    public void Voltar(){
        i -= 10;
        jLPag.setText("Página:"+(i/10+1)+"");
        if (i == 0) {
            jBVoltar.setEnabled(false);
        }
    }
    
}


